# Generated by Django 4.2.11 on 2024-09-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=15, unique=True)),
                ('Number', models.IntegerField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('cpassword', models.CharField(max_length=15)),
            ],
        ),
    ]
